spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123

mybatis-plus:
#  实体扫描 多个文件用,或者;分隔
#  typeAliasesPackage: com.digitalbase.datasource.bean
logging:
  level:
    root: warn
    com.digitalbase.datasource.dao: trace
  pattern:
    console: '%p%m%n'
server:
  port: 9981
