spring:
  profiles:
    active: debug
mybatis:
  type-aliases-package: com.digitalbase.datasource.beans
  mapper-locations: classpath:**/xml/*.xml
logging:
  level:
    com:
      laowang:
        datasource:
          mapper: debug
---
#alpha
spring:
  profiles: run

server:
  port: 1000

---
#beta
spring:
  profiles: debug
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/employees?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123
    ds2:
      jdbc-url: jdbc:mysql://127.0.0.1:33062/world?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root

server:
  port: 8964

parse-file-path: D:\Test
#端口是不会变的, 从配置文件读取即可
mysql-server-port: 3306
default-ds: ds1

---
#dongguan
spring:
  profiles: dongguan

server:
  port: 1002

---
#通用区
spring:
  profiles: general

server:
  port: 1002
---
#gamma
spring:
  profiles: gamma

server:
  port: 1002
