package com.digitalbase.datasource.mapper;

import com.digitalbase.datasource.beans.Salaries;
import com.digitalbase.datasource.beans.SalariesExample;
import com.digitalbase.datasource.beans.SalariesKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SalariesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int countByExample(SalariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int deleteByExample(SalariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SalariesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int insert(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int insertSelective(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    List<Salaries> selectByExample(SalariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    Salaries selectByPrimaryKey(SalariesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Salaries record, @Param("example") SalariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Salaries record, @Param("example") SalariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Salaries record);
}