package com.digitalbase.datasource.mapper;

import com.digitalbase.datasource.beans.Titles;
import com.digitalbase.datasource.beans.TitlesExample;
import com.digitalbase.datasource.beans.TitlesKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TitlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int countByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int deleteByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TitlesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int insert(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int insertSelective(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    List<Titles> selectByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    Titles selectByPrimaryKey(TitlesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Titles record, @Param("example") TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Titles record, @Param("example") TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Titles record);
}